apiVersion: v1
kind: ServiceAccount
metadata:
  name: webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-v2
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-protocol: "http"
        consul.hashicorp.com/connect-service-port: "5000"
        consul.hashicorp.com/connect-service-upstreams: "external-counting:9001:cluster-1"
        consul.hashicorp.com/service-tags: "v2"
        consul.hashicorp.com/service-meta-version: "v2"
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: webapp:v2
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: http
        env:
        - name: COUNTING_SERVICE_URL
          value: "http://localhost:9001"
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
  - protocol: TCP
    port: 5000
  selector:
    app: webapp
  type: NodePort